def get_elevated_response() -> str:
    """
    Return a fixed response for elevated safety concerns.

    This response is intentionally not generated by an LLM.
    """

    return (
        "I'm hearing a lot of distress in what you're describing, "
        "and I want to take that seriously.\n\n"
        "If you feel that you might hurt yourself, or you're not "
        "sure you can stay safe, please contact local emergency "
        "services or a crisis support service. If possible, "
        "consider reaching out to someone you trust who can stay "
        "with you.\n\n"
        "If you are currently safe, you can continue writing here. "
        "ReflectAI can help you reflect on what you're experiencing, "
        "but it is not a therapist or medical professional."
    )