from safety.helplines import get_helplines


def get_crisis_response(country_code: str = "IN") -> str:
    """
    Return a fixed crisis response.

    This message is intentionally not generated by an LLM.
    """

    helplines = get_helplines(country_code)

    lines = [
        "I'm really sorry you're dealing with something this intense.",
        "",
        "I can't provide crisis counseling, but you don't have to handle "
        "an immediate safety concern alone.",
        "",
        "If you may act on thoughts of harming yourself or someone else, "
        "please contact local emergency services or go to the nearest "
        "emergency department.",
        "",
        f"**{helplines['country']} support:**"
    ]

    for resource in helplines["resources"]:
        lines.append(
            f"- **{resource['name']}: {resource['phone']}** "
            f"({resource['description']})"
        )

    lines.extend([
        "",
        "If you can, consider moving to a safer place and contacting "
        "someone you trust who can stay with you.",
        "",
        "ReflectAI is an AI journaling companion, not a therapist "
        "or medical professional."
    ])

    return "\n".join(lines)